# Generated by Django 4.2.1 on 2023-05-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogVersions',
            fields=[
                ('blog_version_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('body_text', models.TextField()),
                ('modified_date', models.DateField(auto_now_add=True)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
            ],
        ),
    ]
